---
name: bosh-plugin

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm
  include:
    jobs:
    - name: plugin-manager
      release: plugin-manager

releases:
- name: plugin-manager
  version: create
  url: file://.
- name: "bpm"
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: bosh-plugin
  azs: [z1]
  instances: 1
  persistent_disk: 10240 # MB
  networks:
  - name: default
  stemcell: default
  vm_type: m3.large
  jobs:
  - name: plugin-manager
    release: plugin-manager
#    properties: